#!/bin/sh

set -o errexit
set -o nounset

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

# migrate changes
python /app/manage.py migrate

# Update the django_site to apartmenthelper.com
postgres_update() {
python << END
import sys

import psycopg2

try:
    connection = psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${POSTGRES_HOST}",
        port="${POSTGRES_PORT}",
    )
    cursor = connection.cursor()
    sql_update_query = """Update django_site set id = %s, domain = %s, name = %s"""
    cursor.execute(sql_update_query, (1, 'apartmenthelper.com', 'apartmenthelper.com'))
    connection.commit()
    count = cursor.rowcount
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}

until postgres_update; do
  >&2 echo 'Waiting for PostgreSQL to UPDATE...'
  sleep 1
done
>&2 echo 'PostgreSQL is UPDATED.'

python /app/manage.py runserver 0.0.0.0:8000
