version: '3'

volumes:
  local_postgres_data: {}

services:
  django: &django
    build:
      context: ..
      dockerfile: ./docker/local/django/Dockerfile
    image: apartmenthelper_local_django
    depends_on:
      - postgres
      - redis
      # - celery
    volumes:
      - ../django:/app:delegated
    env_file:
      - .envs/.local/.django
      - .envs/.local/.postgres
      - .envs/.local/.redis
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: ..
      dockerfile: docker/local/postgres/Dockerfile
    image: apartmenthelper_local_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
    env_file:
      - .envs/.local/.postgres

  react:
    build:
      context: ..
      dockerfile: docker/local/react/Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true  # https://github.com/facebook/create-react-app/issues/8688
    image: apartmenthelper_local_react
    depends_on:
      - django
    volumes:
      - ../react/src:/app/src:delegated
    env_file:
      - .envs/.local/.react
    ports:
      - "3000:3000"
    command: /start
  
  redis:
    build:
      context: ..
      dockerfile: docker/local/redis/Dockerfile
    image: apartmenthelper_local_redis
    env_file:
      - .envs/.local/.redis

  celery:
    <<: *django  # Extend the django service
    image: apartmenthelper_local_celeryworker
    ports: []
    command: /start-celeryworker

  flower:  
    <<: *django  # Extend the django service
    image: mher/flower
    command:  ["flower", "--broker=redis://default:ewxzyepWcKoIYpsMrzLfSKGnQpjCBoDKOHnhDKgmCHcfhVEFRX@redis:6379/0", "--port=8888"]
    environment:
      - FLOWER_PORT=8888
    ports:  
      - 8888:8888
    depends_on:
     - redis
     - celery
